### ISSUE TITLE
org.embulk.spi.time.TimestampParseException: Failed to parse '2015-05-20 21:34:02 UTC'

### ISSUE THREAD

**Issue by sonots** [shun0102/embulk-parser-jsonl#7]
I want to read JSON files exported from BigQuery. 
The export feature of BigQuery converts its TIMESTAMP columns as of form:

```
2015-05-20 21:34:02 UTC
```

or, for millisenconds:

```
2015-05-20 21:34:02.1 UTC
2015-05-20 21:34:02.123456 UTC
```

However, configuring embulk-parser-jsonl as

```
columns:
- { name: time, type: timestamp }
```

results in an error

```
org.embulk.spi.time.TimestampParseException: Failed to parse '2015-05-20 21:34:02 UTC'
```

FYI: BigQuery's TIMESTAMP column is only UTC
FYI: BigQuery API does not have configuration for timestamp format on exporting.

**Comment by muga** [comment]
I still might not catch what you're saying.

My understanding is that your points are: When you tried to export data from BigQuery,

a. 2 types of time formats like `'%Y-%m-%d %H:%M:%S %z'` and `'%Y-%m-%d %H:%M:%S.%N %z'` existed in one timestamp column. 

b. To parse both of time formats in the column, you tried to specify `{name: time, type: timestamp}` without using `format`, but it didn't work. 

Is it correct? (If not, please correct me.) Regarding a, The feature is not supported by embulk-parser-jsonl. Embulk as well. embulk-parser-jsonl uses Embulk's default timestamp parser, it's better to file an issue ticket in Embulk itself. Regarding b, the reason why it didn't work is because `'%Y-%m-%d %H:%M:%S.%N %z'` was used as default format. 

As one of approach to solve this problem, I think that you specify string type instead of timestamp and develop a filter plugin for parsing several timestamp formats. Does it make sense?

**Comment by sonots** [comment]
1st, I was misunderstanding that this plugin does not have format option since it is not documented on README and reading codes gave me impression like this line of codes was doing something like ruby's Time.parse https://github.com/shun0102/embulk-parser-jsonl/blob/master/src/main/java/org/embulk/parser/jsonl/getter/CommonColumnGetter.java#L103. Thank you for letting me know.

2nd, I agree that I should create a new filter plugin because my case requires two possible formats. It is reasonable. Thanks!
